FROM postgres

RUN localedef -i ru_RU -c -f UTF-8 -A /usr/share/locale/locale.alias ru_RU.UTF-8
ENV LANG ru_RU.utf8

#COPY docker/db/postgresql.conf /var/lib/postgresql/data/postgresql.conf
#
#COPY docker/db/init.sql /docker-entrypoint-initdb.d/

